[package]
name = "mmtk"
version = "0.0.1"
authors = [" <>"]

[lib]
name = "mmtk"
crate-type = ["rlib", "dylib", "staticlib"]
doctest = false

[dependencies]
libc = "0.2"
lazy_static = "1.0"
env_logger = "0.4.3"
log = "0.4.1"

[features]
default = ["nogc"]
nogc = []
semispace = []
jikesrvm = []
