name: Post Code Review Checks

on:
  pull_request:
#    types:
#      - labeled
    branches:
      - master

jobs:
  jikesrvm-binding-test:
    runs-on: ubuntu-18.04
#    if: contains(github.event.pull_request.labels.*.name, 'PR-approved')
    steps:
      - name: Checkout MMTk Core
        uses: actions/checkout@v2
        with:
          path: mmtk-core
      - name: Checkout JikesRVM Binding
        uses: actions/checkout@v2
        with:
          repository: mmtk/mmtk-jikesrvm
          token: ${{ secrets.CI_ACCESS_TOKEN }}
          path: mmtk-jikesrvm
          submodules: true
      - name: Overwrite MMTk core in JikesRVM binding
        run: |
          set -x
          ls -l mmtk-core
          cat mmtk-core/src/mm/memory_manager.rs
          ls -l mmtk-jikesrvm/repos/mmtk-core
          cat mmtk-jikesrvm/repos/mmtk-core/src/mm/memory_manager.rs
          rsync -avLe mmtk-core/* mmtk-jikesrvm/repos/mmtk-core/
          ls -l mmtk-jikesrvm/repos/mmtk-core
          cat mmtk-jikesrvm/repos/mmtk-core/src/mm/memory_manager.rs
      - name: Setup
        run: |
          cd mmtk-jikesrvm
          ls
          ./.github/scripts/ci-setup.sh
      - name: Test
        run: |
          cd mmtk-jikesrvm
          ./.github/scripts/ci-test.sh